# Generated by Django 4.1.3 on 2022-11-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=5)),
                ('JISCodePoint', models.CharField(blank=True, max_length=20, null=True)),
                ('unicode', models.CharField(blank=True, max_length=20, null=True)),
                ('classicalRadical', models.IntegerField(blank=True, null=True)),
                ('NelsonRadical', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('strokeCount', models.IntegerField(blank=True, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('radical', models.CharField(blank=True, max_length=5, null=True)),
                ('JLPT', models.IntegerField(blank=True, null=True)),
                ('dicNelsonClassic', models.IntegerField(blank=True, null=True)),
                ('dicNelsonNew', models.CharField(blank=True, max_length=20, null=True)),
                ('dicHalpernNJECD', models.IntegerField(blank=True, null=True)),
                ('dicKodanshaKanji', models.IntegerField(blank=True, null=True)),
                ('dicKanjiLearners', models.IntegerField(blank=True, null=True)),
                ('dicKanjiLearners2', models.IntegerField(blank=True, null=True)),
                ('dicHeisig', models.IntegerField(blank=True, null=True)),
                ('dicHeisig6', models.IntegerField(blank=True, null=True)),
                ('dicGakken', models.IntegerField(blank=True, null=True)),
                ('dicOneillNames', models.CharField(blank=True, max_length=20, null=True)),
                ('dicOneillKk', models.IntegerField(blank=True, null=True)),
                ('dicMorohashi', models.CharField(blank=True, max_length=50, null=True)),
                ('dicHenshall', models.IntegerField(blank=True, null=True)),
                ('dicKanjiKana', models.IntegerField(blank=True, null=True)),
                ('dicKanjiKana2011', models.IntegerField(blank=True, null=True)),
                ('dicSakade', models.IntegerField(blank=True, null=True)),
                ('dicJapaneseKanjiFlashcards', models.IntegerField(blank=True, null=True)),
                ('dicHenshall3', models.IntegerField(blank=True, null=True)),
                ('dicTuttleCards', models.IntegerField(blank=True, null=True)),
                ('dicCrowley', models.IntegerField(blank=True, null=True)),
                ('dicKanjiContext', models.IntegerField(blank=True, null=True)),
                ('dicKodanshaCompact', models.IntegerField(blank=True, null=True)),
                ('dicJapaneseBusyPeople', models.CharField(blank=True, max_length=20, null=True)),
                ('dicManiette', models.IntegerField(blank=True, null=True)),
                ('skip', models.CharField(blank=True, max_length=15, null=True)),
                ('SandH', models.CharField(blank=True, max_length=15, null=True)),
                ('fourCorner', models.CharField(blank=True, max_length=15, null=True)),
                ('deRoo', models.CharField(blank=True, max_length=15, null=True)),
                ('onyomi', models.CharField(blank=True, max_length=15, null=True)),
                ('kunyomi', models.CharField(blank=True, max_length=15, null=True)),
                ('nanori', models.CharField(blank=True, max_length=15, null=True)),
                ('meaningEn', models.CharField(blank=True, max_length=100, null=True)),
                ('meaningEs', models.CharField(blank=True, max_length=100, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('ethimology', models.TextField(blank=True, null=True)),
                ('nemonics', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
